// <auto-generated />
using System;
using IpBlockerNetcore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IpBlockerNetcore.Migrations
{
    [DbContext(typeof(IpBlockerNetcoreContext))]
    [Migration("20230509165253_dfsfdf")]
    partial class dfsfdf
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IpBlockerNetcore.Models.Domain.BanLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("BanLog");
                });

            modelBuilder.Entity("IpBlockerNetcore.Models.Domain.BlackList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DangerLevel")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("IpAdresiId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IpAdresiId");

                    b.ToTable("BlackList");
                });

            modelBuilder.Entity("IpBlockerNetcore.Models.Domain.Entry", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("clientIpAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("protocol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("qclass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("qname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("qtype")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("responseType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("rowNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Entry");
                });

            modelBuilder.Entity("IpBlockerNetcore.Models.Domain.IPAddresi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("IPAddressBytes")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varbinary(16)");

                    b.HasKey("Id");

                    b.ToTable("IPAddresi");
                });

            modelBuilder.Entity("IpBlockerNetcore.Models.Domain.ScanIp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("IpAdresiId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IpAdresiId");

                    b.ToTable("ScanIp");
                });

            modelBuilder.Entity("IpBlockerNetcore.Models.Domain.WhiteList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DangerLevel")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("IpAdresiId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IpAdresiId");

                    b.ToTable("WhiteList");
                });

            modelBuilder.Entity("IpBlockerNetcore.Models.Domain.BlackList", b =>
                {
                    b.HasOne("IpBlockerNetcore.Models.Domain.IPAddresi", "IpAdresi")
                        .WithMany()
                        .HasForeignKey("IpAdresiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IpAdresi");
                });

            modelBuilder.Entity("IpBlockerNetcore.Models.Domain.ScanIp", b =>
                {
                    b.HasOne("IpBlockerNetcore.Models.Domain.IPAddresi", "IpAdresi")
                        .WithMany()
                        .HasForeignKey("IpAdresiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IpAdresi");
                });

            modelBuilder.Entity("IpBlockerNetcore.Models.Domain.WhiteList", b =>
                {
                    b.HasOne("IpBlockerNetcore.Models.Domain.IPAddresi", "IpAdresi")
                        .WithMany()
                        .HasForeignKey("IpAdresiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IpAdresi");
                });
#pragma warning restore 612, 618
        }
    }
}
